### ISSUE TITLE
As for the encryption 

### ISSUE THREAD

**Issue by WataruD** [AlexRazor1337/mta-model-encoder#2]
Help me understand how it works
I used the example, it encrypted, changed values in meta.xml
But it didn't change anything in client
Lua

**Comment by AlexRazor1337** [comment]
Maybe you'll have a problem if you already have file named "client.lua". So the script should create "client.lua" file which modifies default "engineLoad*" functions behavior and the new resource should just work

**Comment by WataruD** [comment]
The thing is, it doesn't create a lua file.

**Comment by WataruD** [comment]
If you have time, could you please go to Discord and add me.
My Discord limbod

**Comment by AlexRazor1337** [comment]
> The thing is, it doesn't create a lua file.

Ah, sorry, I forgot a bit how it works. So you **must** have `client.lua` file when using **--full** option. I will need to update a script and a README file to reflect this. This client file may have additional logic in it, but I believe it's best when it's simple (so for example just engine load and replace functions). All `engineLoad*` functions will be replaced with `decodeLoad*` which are custom function to handle decoding process. And all this client side code(client.lua content and additional code) will be placed into `_decoder_client.lua` file at resource directory. 

So you will need -f AND -m options for this to work,

Try this again, I'll try to contact you in a Discord when I will be available

**Comment by WataruD** [comment]
![11](https://github.com/AlexRazor1337/mta-model-encoder/assets/154073520/b3a2ecf9-7416-4eb1-a38f-e637917930c8)
![22](https://github.com/AlexRazor1337/mta-model-encoder/assets/154073520/02677270-c809-42b1-9ad2-477bf52daac5)
I did as you said but the model does not want to load in the debug no errors model is not replaced

**Comment by AlexRazor1337** [comment]
Does it not work with "reloadcar" command too? Because onClientResourceStart probably will not work, as it's getting added after resource start. Or try even without the function, just load and import. I may create workaround for start event later.

**Comment by WataruD** [comment]
![elegy](https://github.com/AlexRazor1337/mta-model-encoder/assets/154073520/94585c20-9bca-4ba5-933b-9705942922c2)
![elegy2](https://github.com/AlexRazor1337/mta-model-encoder/assets/154073520/ba90adb4-850f-420d-aad8-fba4791da1e1)
I did what you advised me to do, now I get an error in the console.

**Comment by WataruD** [comment]
I was able to load the model only after writing reloadcar, how to make it so that the model is replaced immediately after the start of the resource and I understand correctly that in the resource should always be encrypted model and without encryption, only if you load for example a model that has an open model, then the owners of hosting will be able to steal it.

**Comment by AlexRazor1337** [comment]
To replace the model immediately you don't need any function or onClientResourceStart event. Just place load and replace code directly and it will run as soon as possible.

Resource encryption is needed because any player can go into MTA folder and see client files of resources from your server. And if the model is encrypted, then player will get just some file with no way to use it.
